# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  V3D_config = debug
endif
ifeq ($(config),release)
  V3D_config = release
endif

PROJECTS := V3D

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

V3D:
ifneq (,$(V3D_config))
	@echo "==== Building V3D ($(V3D_config)) ===="
	@${MAKE} --no-print-directory -C . -f V3D.make config=$(V3D_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f V3D.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   V3D"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"